version: "3.9"

services:
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=universal
      - POSTGRES_USER=maximo
      - POSTGRES_PASSWORD=UPbeat123
    volumes:
      - my-db:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: maximugisha@gmail.com
      PGADMIN_DEFAULT_PASSWORD: UPbeat123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database
    networks:
      - network

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:3001
#    env_file: .env
    volumes:
      - .:/code
    ports:
      - "3001:3001"
    depends_on:
      - database
    networks:
      - network

  universal_frontend:
    restart: always
    command: npm start
    container_name: universal_frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - .:/code
      - node_modules:/code/frontend/node_modules
    depends_on:
      - backend

networks:
  network:
    driver: bridge


volumes:
  my-db: #for postgres
  pgadmin-data:
  node_modules: