version: "3"

services:
  db: #name same as host
    env_file: .env
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - my-db:/var/lib/postgresql/data
    networks:
      - network

  backend:
    image: backend
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network


networks:
  network:
    driver: bridge


volumes:
  my-db: #for postgres
