name: Universal CI/CD

on: push

jobs:
  execute_tests: #Job id
    name: Install requirements and execute test
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
        name: Update

