name: Universal CI/CD

on: push

jobs:
  execute_tests: #Job id
    name: Universal App setup # Job name
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
        name: Update
      - name: Checkout Repo COde
        uses: actions/checkout@v3

